name: CI Pipeline

on:
  push:
    branches:
      - 'main'
      - 'develop'
      - 'fix/integration-test'
  pull_request:
    branches:
      - 'main'
      - 'develop'
      
jobs:
  test:
    runs-on: [F74134710]

    steps:
      - name: Clear and Set Permissions for Temp Folder
        run: |
          Remove-Item -Recurse -Force "${{ runner.temp }}\*"
          icacls "${{ runner.temp }}" /grant Everyone:F /T
        shell: powershell
      
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache-dependency-path: |
            backend/requirements.txt

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt
          pip install pytest pytest-mock pytest-cov

      - name: Run unit tests
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          OPEN_AI_API_KEY: ${{ secrets.OPEN_AI_API_KEY }}
          SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
          USER_ACCESS_TOKEN_SECRET_KEY: ${{ secrets.USER_ACCESS_TOKEN_SECRET_KEY }}
        run: |
          cd backend
          pytest tests/unit --cov=src --cov-report=xml --disable-warnings

      - name: Run integration tests (with mock DB)
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          OPEN_AI_API_KEY: ${{ secrets.OPEN_AI_API_KEY }}
          SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
          USER_ACCESS_TOKEN_SECRET_KEY: ${{ secrets.USER_ACCESS_TOKEN_SECRET_KEY }}
        run: |
          cd backend
          pytest tests/integration --cov=src --cov-report=xml --disable-warnings

      - name: Upload coverage report
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: coverage.xml

  # lint:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v3

  #     - name: Set up Python
  #       uses: actions/setup-python@v4
  #       with:
  #         python-version: "3.12"

  #     - name: Install dependencies
  #       run: |
  #         python -m pip install --upgrade pip
  #         pip install flake8

  #     - name: Run flake8
  #       run: |
  #         flake8 backend --count --max-line-length=150 --statistics